version: '3.6'

services:
  api:
    build: ./app
    command: gunicorn reimbursinator.wsgi:application --bind 0.0.0.0:81
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:81
    environment:
      - SECRET_KEY=please_change
  web:
    image: nginx:1.10.3
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=reimbursinator.com
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
