version: '3.6'

services:
  api:
    build: ./app
    command: gunicorn reimbursinator.wsgi:application --bind 0.0.0.0:444 --keyfile /etc/ssl/selfsigned.key --certfile /etc/ssl/selfsigned.crt
    volumes:
      - ./app/:/usr/src/app/
      - ./config/selfsigned.key:/etc/ssl/selfsigned.key
      - ./config/selfsigned.crt:/etc/ssl/selfsigned.crt
    ports:
      - "8444:444"
    environment:
      - SECRET_KEY=please_change
  web:
    image: nginx:1.10.3
    volumes:
      - ./static:/usr/share/nginx/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/selfsigned.key:/etc/ssl/selfsigned.key
      - ./config/selfsigned.crt:/etc/ssl/selfsigned.crt
    ports:
      - "8443:443"
    environment:
      - NGINX_HOST=reimbursinator.com
      - NGINX_PORT=443
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
